### ISSUE TITLE
Problem with other tif archives

### ISSUE THREAD

**Issue by Regittos** [ptarroso/MapAnim#1]
I need some help please.

I'm trying to use your code with the tif archives that i have, but none of them works your code

I change the: metadata of the tif file, classdata file and elements.json and doesn't work

When I open in the Qgis, don't see the diference

Here is the error:
![Sem título](https://github.com/ptarroso/MapAnim/assets/107368603/87979f29-df17-440e-bf8c-10701c54d111)

And here are files that i have using
[test.zip](https://github.com/ptarroso/MapAnim/files/12862149/test.zip)

I want to know if is the csv, json or the tif file

**Comment by ptarroso** [comment]
Hi @Regittos 

Thanks for your interest. I believe that is the classdata.csv. As it is, the code requires that all classes in the csv file can be found in the tif file, which is not your case. You classes number 14, 18, 19, and 20 are in the csv but not in the raster. Remove the respective lines in the csv and the script will work. 

Note that for using that json it is expected to have the fonts in you execution folder.
